module.exports = {
    tweetOld: [
        '<div class="row">',
        '<div class="col-sm-12 photo-box">',
        '<img class="img-responsive" src=<%= avatar %> alt="Chania">',
        '</div>',
        '</div>',
        '<div class="row">',
        '<div class="col-sm-7 text-left">',
        '<h5><%= author %> <span class="glyphicon glyphicon-ok-sign text-primary" aria-hidden="true"></span><span class="text-muted"> @<%= handle %> - <%= date %></span></h5>',
        '</div>',
        '<div class="col-sm-5 text-right">',
        '<h5>',
        '<ul class="text-muted">',
        '<li class="retweets"><span class="glyphicon glyphicon-retweet" aria-hidden="true"></span><strong>1.7K</strong></li>',
        '<li class="likes"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span><strong>6.7K</strong></li>',
        '<li><span class="glyphicon glyphicon-option-horizontal" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="More"></span></li>',
        '</ul>',
        '</h5>',
        '</div>',
        '</div>',
        '<div class="row">',
        '<div class="col-sm-12 text-left">',
        '<p>',
        '<%= content %>',
        '</p>',
        '</div>',
        '</div>',
    ].join(''),

    tweet: [
        '<div class="row">',
        '<div class="avatar">',
        '<img src=<%= avatar %> class="img-rounded" alt="Avatar" width="48" height="48">',
        '</div>',
        '<div class="tweetails text-left">',
        '<div class="">',
        '<h5><strong><%= author %></strong> <span class="text-muted">@<%= handle %> - <%= date %></span></h5>',
        '</div>',
        '<div class="">',
        '<form role="form" class="hidden">',
        '<div class="form-group">',
        '<input type="text" class="form-control" name="edit-tweet" value="<%= content %>">',
        '</div>',
        '</form>',
        '<p>',
        '<%= content %>',
        '</p>',
        '</div>',
        '<div class="">',
        '<h5>',
        '<ul class="text-muted">',
        '<li class="retweets"><span class="glyphicon glyphicon-retweet" aria-hidden="true"></span><strong>1.7K</strong></li>',
        '<li class="likes"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span><strong>6.7K</strong></li>',
        '<li class="dropdown">',
        '<span class="glyphicon glyphicon-option-horizontal dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></span>',
        '<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">',
        '<li><a href="#" class="edit-tweet">Edit tweet</a></li>',
        '<li><a href="#" class="delete-tweet">Delete tweet</a></li>',
        '</ul>',
        '</li>',
        '<li><span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span></li>',
        '</ul>',
        '</h5>',
        '</div>',
        '</div>',
        '</div>',
    ].join(''),

    newTweet: [
        '<form role="form">',
        '<div class="form-group text-left">',
        '<textarea class="form-control" id="tweet-content"></textarea>',
        '</div>',
        '<button type="submit" class="btn btn-info btn-block">Submit</button>',
        '</form>',
    ].join(''),
};
